-- Architecture & Flow page — generated from apps/api/prisma/architecture-page.ts.
-- Mirrors the MALKOM_3.0_Architecture_and_Flow workbook (Overview sheet skipped).
-- Rerunnable: replaces the page and its content; nothing else is touched.
begin;
delete from "ContentRevision" where "blockId" in (select cb.id from "ContentBlock" cb join "Section" s on s.id=cb."sectionId" where s."pageId" in (select id from "Page" where slug='architecture'));
delete from "ContentBlock" where "sectionId" in (select id from "Section" where "pageId" in (select id from "Page" where slug='architecture'));
delete from "Section" where "pageId" in (select id from "Page" where slug='architecture');
delete from "Page" where slug='architecture';
insert into "Page" (slug, title, summary, "order")
values ('architecture', 'Architecture & Flow', 'Bookings flow, layered architecture & tech stack, modules, roles and core engines — the consolidated MALKOM 3.0 blueprint.', (select coalesce(max("order"), -1) + 1 from "Page"));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='architecture'), 'flow-diagram', 'Flow Diagram', 'Queues → Agentic Queue & STP decision → manual allocation, states, metrics & analytics', 0);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='flow-diagram'), null, 'RICH_TEXT', $j${"markdown":"![MALKOM 3.0 Framework — bookings flow, system architecture, tech stack, modules, roles and core engines](/architecture-poster.png)"}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='architecture'), 'tech-stack', 'Tech Stack', 'Layer-by-layer technology choices for MALKOM 3.0', 1);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='tech-stack'), null, 'RICH_TEXT', $j${"markdown":"System architecture — layer-by-layer technology choices for MALKOM 3.0."}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='tech-stack'), null, 'DATA_TABLE', $j${"columns":["Layer","Component","Details"],"rows":[["🖥 Front end","React + Radix + shadcn/ui","—"],["🖥 Front end","TailwindCSS","—"],["🖥 Front end","Material Icons","—"],["🔌 API stack","TypeScript / Vite","—"],["🔌 API stack","Node.js","As npm"],["🔌 API stack","PostgREST + Prisma + Zod","—"],["⚡ Cache","Valkey","In-memory cache between API and data"],["🗄 Data / backend","PostgreSQL","Transaction and MDM instances"],["🗄 Data / backend","Transaction DB","Primary and secondary failovers"],["🗄 Data / backend","Vector DB","—"],["⚙ Services","File Storage","AWS S3 • Azure Blob Storage • GCP Storage • On-premise MinIO"],["⚙ Services","Connectors / Adapters","Cloud providers → AAG • storage connectors • database storage connectors • DB adapters"],["⚙ Services","SFTP & Email connectors","—"],["⚙ Services","Agentic Framework","—"],["⚙ Services","Observability","In-built DB logs / cloud logs"],["⚙ Services","ML","ML framework, deployment and training environment"]],"caption":"Layer-by-layer technology choices (from the brainstorm workbook)"}$j$::jsonb, 1, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='architecture'), 'booking-flow', 'Booking Flow', 'How a booking travels through queues, states, statuses and metrics', 2);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'RICH_TEXT', $j${"markdown":"### 📥 Entry point & queue model\n\nWork starts from the list of all open booking requests, organised into queues:"}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'DATA_TABLE', $j${"columns":["Concept","Definition"],"rows":[["Q (parent queue)","The parent queue — e.g. Booking, BOL Creation or Support."],["Sub-Q (child queue)","The child queue under a Q — in Booking: New, Amendment… • in BOL Creation: BL Draft, BL Rating…"],["Agentic Queue","Tasks from Q / Sub-Q land in the Agentic Queue first — the Agentic Framework attempts automated straight-through processing before any manual touch."]]}$j$::jsonb, 1, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'RICH_TEXT', $j${"markdown":"### 🤖 STP decision — All OK?"}$j$::jsonb, 2, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'DATA_TABLE', $j${"columns":["Outcome","What happens"],"rows":[["YES","Auto-processed (STP) — no manual allocation; the task goes straight to Track & Measure."],["NO","Manual handling — the task is routed to the Work Allocation Engine, which runs the Allocation Matrix."]],"caption":"Straight-Through Processing check — every task passes through it after the Agentic Queue"}$j$::jsonb, 3, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'RICH_TEXT', $j${"markdown":"### 🏷 States & status"}$j$::jsonb, 4, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'DATA_TABLE', $j${"columns":["Group","Values"],"rows":[["Booking states","NEW • AMENDMENT • CANCELLED • SPLIT • CONFIRMED"],["Workflow transaction states","INDEXED (REGISTERED) • PROCESSED • PARKED • QUERY"],["Workflow transaction status","OPEN → WIP → CLOSED (progresses left → right)"]],"caption":"Every incoming request is classified into one of the booking states"}$j$::jsonb, 5, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'RICH_TEXT', $j${"markdown":"### ⏱ Timestamps & allocation property"}$j$::jsonb, 6, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'DATA_TABLE', $j${"columns":["Property","Detail"],"rows":[["Transaction timestamps","Every state + status combination carries its own timestamp."],["WF allocation property","Allocate To • When (timestamp) • Trans Start • Trans Touch • Trans End"]]}$j$::jsonb, 7, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'RICH_TEXT', $j${"markdown":"### 📊 Metrics & analytics"}$j$::jsonb, 8, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='booking-flow'), null, 'DATA_TABLE', $j${"columns":["Metric group","Measures"],"rows":[["Task metrics","AHT • TAT (states) • TAT (overall)"],["Q metrics","BK TAT • BK Aging"],["Audit log metrics","Task change • Update history (new / old value) • Event state"],["Analytics","My Performance Dashboard — user • Realtime Q & Sub-Q Dashboard — admin • SLA / volume / aging trends • Audit & update history"]],"caption":"Both STP and manually worked tasks converge in Track & Measure — every task is tracked"}$j$::jsonb, 9, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='architecture'), 'modules-pages', 'Modules & Pages', 'What each persona sees in the MALKOM 3.0 front end', 3);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='modules-pages'), null, 'RICH_TEXT', $j${"markdown":"### 👤 User — Offshore / Onshore"}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='modules-pages'), null, 'DATA_TABLE', $j${"columns":["#","Page / capability"],"rows":[["1","My Task / My Q — action on list"],["2","Task detail (Q state / workflow state & status) — action on task"],["3","Search tasks and edit all items (based on roles set)"],["4","My performance dashboard"],["5","Edit booking queue information across the life cycle"],["6","Exit task status updates — transfer, query creation (query life cycle)"],["7","Task life cycle"]]}$j$::jsonb, 1, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='modules-pages'), null, 'RICH_TEXT', $j${"markdown":"### 🛡 Admin"}$j$::jsonb, 2, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='modules-pages'), null, 'DATA_TABLE', $j${"columns":["#","Page / capability"],"rows":[["1","Admin dashboard — real-time status of every Q and Sub-Q (volume, allocation, status)"],["2a","Offshore user profiling — user creation, activation, roles, Q management, capacity management • backup profiling"],["2b","Onshore user profiling — user creation, activation, roles, Q management, capacity management"],["3","Search tasks not assigned (based on roles set)"],["4","Admin search — everything"],["5","Rules setup — Q (field and combination based) / Sub-Q / task / validity → approval based"],["6","Template creation — depending on the state of the Q or task"],["7","List of exceptions — country / region / Q; create and maintain exception lists / maps for onshore and offshore departments"]]}$j$::jsonb, 3, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='modules-pages'), null, 'RICH_TEXT', $j${"markdown":"### 👑 Super / Dev / IT Admin\n\nFull platform control — sets up and monitors the core engines listed on the Engines & Allocation tab."}$j$::jsonb, 4, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='modules-pages'), null, 'DATA_TABLE', $j${"columns":["#","Page / capability"],"rows":[["★","Everything available to User and Admin"],["1","Dev configs / app settings"],["2","Q creation / Q modifications / Q management"],["3","Monitoring — audit logs • invariant behaviour (monitoring alerts) • SLA resource metrics for hardware and software"],["4","DB access management"],["5","ML pipeline creation / setup / dependencies • monitor ML pipeline (classification or categorisation)"],["6","API management — incoming (from client) and outgoing (to client)"],["7","API key vault management"],["8","Billing and parent data management — billing patterns by Q / Sub-Q / task and others; SLA clauses and rewards"]]}$j$::jsonb, 5, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='architecture'), 'engines-allocation', 'Engines & Allocation', 'How work gets allocated, and the platform services running underneath', 4);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='engines-allocation'), null, 'RICH_TEXT', $j${"markdown":"### 🎯 Allocation Matrix"}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='engines-allocation'), null, 'DATA_TABLE', $j${"columns":["Property","Detail"],"rows":[["Allocation properties","Country • Region • Office • Q • Sub-Q • Task states • Capacity"],["Pseudo properties","Every Q comes with additional props → rule-based allocation on any combination of Q and Sub-Q properties"],["Run by","Work Allocation Engine — non-STP tasks are routed here for manual handling; it executes the rules for the Allocation Matrix"]]}$j$::jsonb, 1, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='engines-allocation'), null, 'RICH_TEXT', $j${"markdown":"### ⚙ Core engines & services"}$j$::jsonb, 2, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='architecture' and s.slug='engines-allocation'), null, 'DATA_TABLE', $j${"columns":["Engine / service","Notes"],"rows":[["Validation Engine","—"],["Work Allocation Engine","Rules for the Allocation Matrix to run"],["Agentic Setup & Monitoring","—"],["RBAC / Identity Auth","OFA / UP / SSO setup"],["Workflow Management","—"],["Metrics Engine","Task · Q · audit metrics"],["Document / File Management","Storage / events"],["Email Management Service","—"],["SFTP","Client data input or output"],["Master Data Management","—"],["AI Provider Management","Usage / maintenance"]],"caption":"Notes carried over from the brainstorm workbook"}$j$::jsonb, 3, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
commit;
