-- Client Deployment Model page — generated from apps/api/prisma/deployment-page.ts.
-- Rerunnable: replaces the page and its content; nothing else is touched.
begin;
delete from "ContentRevision" where "blockId" in (select cb.id from "ContentBlock" cb join "Section" s on s.id=cb."sectionId" where s."pageId" in (select id from "Page" where slug='deployment-model'));
delete from "ContentBlock" where "sectionId" in (select id from "Section" where "pageId" in (select id from "Page" where slug='deployment-model'));
delete from "Section" where "pageId" in (select id from "Page" where slug='deployment-model');
delete from "Page" where slug='deployment-model';
insert into "Page" (slug, title, summary, "order")
values ('deployment-model', 'Client Deployment Model', 'Multi-tenant provisioning — parent platform → organization setup → deployment structure.', (select coalesce(max("order"), -1) + 1 from "Page"));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='deployment-model'), 'overview', 'Deployment Model', 'How client organizations are provisioned and where the platform runs', 0);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='deployment-model' and s.slug='overview'), null, 'RICH_TEXT', $j${"markdown":"![MALKOM 3.0 — Deployment Model: multi-tenant provisioning, parent platform, organization setup and deployment structure options](/deployment-poster.png)"}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='deployment-model'), 'provisioning', 'Organization Provisioning — Flow', 'Every client is an organization (tenant), created and configured from the parent platform', 1);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='deployment-model' and s.slug='provisioning'), null, 'DATA_TABLE', $j${"columns":["Step","What happens"],"rows":[["1 · Parent Platform","Central control plane — owns, creates and governs every organization running on MALKOM 3.0. Org management • Platform governance"],["2 · Create New Organization","A new client organization is spun up from the parent platform — an isolated tenant with its own users, data and configuration. Per-org RBAC & data isolation"],["3 · Configure Org Requirements","Per-organization platform setup: Queues — Q & Sub-Q • Deployment structure • Features. The deployment structure is selected here."]]}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='deployment-model'), 'options', 'Deployment Structure — Options', 'Chosen per organization during configuration — same containerized codebase in every model (open architecture)', 2);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='deployment-model' and s.slug='options'), null, 'DATA_TABLE', $j${"columns":["Option","Model","Our cloud (WNS)","Client cloud / on-prem","Best for"],"rows":[["A","Fully hosted — our cloud","Main App + Features","Users — browser / API access only","Fastest onboarding — we run everything; the client consumes via browser & APIs."],["B","Split — features in client cloud","Main App","Features","Data-heavy features stay inside the client environment (data residency / gravity)."],["C","Fully client-hosted","Parent platform — governance only","Main App + Features","Full sovereignty — platform deployed into the client cloud or on-prem (K8s · MinIO)."],["D","Hybrid mix","Main App + Features — set 1","Features — set 2","Per-feature placement — each feature hosted where it fits best, set at org configuration."]],"caption":"One deployment structure is selected per organization"}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
insert into "Section" ("pageId", slug, title, description, "order")
values ((select id from "Page" where slug='deployment-model'), 'common', 'Common to Every Model', 'The deployment choice never changes the product — one open, containerized platform', 3);
insert into "ContentBlock" ("sectionId", "parentId", kind, payload, "order", status, "publishedAt", "createdById")
values ((select s.id from "Section" s join "Page" p on p.id=s."pageId" where p.slug='deployment-model' and s.slug='common'), null, 'DATA_TABLE', $j${"columns":["Guarantee","Detail"],"rows":[["One codebase","Containerized, open architecture — identical in every deployment model"],["Org-scoped configuration","Q & Sub-Q configuration scoped per organization"],["Isolation","RBAC & data isolation per organization"],["Connectivity","AAG connectors bridge clouds — storage · DB · SFTP · email"],["Operations","Central observability, audit & telemetry"],["Features","Toggled per organization"]]}$j$::jsonb, 0, 'PUBLISHED', now(), (select id from "User" where email='system@malkom.local'));
commit;
